name: kitchenassistant
description: AI-powered cooking app with step-by-step illustrated recipes

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Ensure your Dart SDK meets Supabase v2 requirements

dependencies:
  flutter:
    sdk: flutter

  # UI and navigation
  cupertino_icons: ^1.0.5

  # State management
  provider: ^6.0.5

  # Network and API
  http: ^1.1.0

  # Supabase integration - UPGRADED
  supabase_flutter: ^2.8.4 # Upgraded to latest stable (v2)

  # Environment and configuration
  flutter_dotenv: ^5.1.0

  # Image handling
  cached_network_image: ^3.3.0

  # Error monitoring
  sentry_flutter: ^7.16.0  # Added Sentry for error monitoring

  # Utilities
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  share_plus: ^10.1.4  # Added for recipe sharing functionality
  url_launcher: ^6.1.14  # Added for launching URLs and emails
  package_info_plus: ^8.3.0  # Updated to compatible version

  # UI enhancements
  shimmer: ^3.0.0

  # Explicitly add sign_in_with_apple with its latest version
  # Required for Supabase v2 Apple Auth and to fix original build error
  sign_in_with_apple: ^7.0.1 # Using latest stable

  uuid: ^4.3.3
  # sign in with google
  google_sign_in: ^6.3.0
  # facebook auth
  flutter_facebook_auth: ^7.1.2
  purchases_flutter: ^8.8.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/
    - assets/logo.png
    - assets/chat_icon.png
    - assets/empty_recipes.png
    - assets/recipe_placeholder.png
    - assets/profile_placeholder.png
    # Add these for the About screen
    - assets/flutter_logo.png
    - assets/nodejs_logo.png
    - assets/supabase_logo.png
    - assets/openai_logo.png
    # social auth
    - assets/google_logo.png
    - assets/facebook_logo.png
    - assets/apple_logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages